apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-ddd-deployment
  labels:
    app: tp2-ddd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tp2-ddd
  template:
    metadata:
      labels:
        app: tp2-ddd
    spec:
      containers:
      - name: tp2-ddd
        image: tp2_ddd:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tp2-ddd-service
spec:
  type: LoadBalancer 
  selector:
    app: tp2-ddd
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
